### PR TITLE
SLING-12318 apply spotless formatting

### PR DESCRIPTION
**Pull request by joerghoh**
In preparation for an update to a newer parent pom run ``mvn spotless:apply`` to get the formatting right.

### CODE REVIEW

**Comment by joerghoh** [comment]
(failed for not building on Java 21, which I plan to fix asap)

**Comment by rombert** [comment]
@joerghoh - I think I already fixed the Java 21 build ... #45

**Comment by joerghoh** [comment]
@rombert When I tried to make the update of the parent pom and the test dependencies, the spotless plugin failed the build for me; and for that reason I wanted to have the formatting change before I do the update of the pom.

In other words: we need #44 **and** #45 merged (preferably in this order).

**Review by rombert — APPROVED** [review]
OK, let's merge this first then.

**Pull request merged**
