### PR TITLE
SLING-11728 Remove bi-directional dependencies between Engine and Ser…

### PR DESCRIPTION
**Pull request by oliverlietz**
…vlets Resolver

* switch from org.apache.sling.engine.servlets.ErrorHandler to org.apache.sling.api.servlets.ErrorHandler
* remove org.apache.sling.engine.servlets.ErrorHandler

### CODE REVIEW

**Comment by oliverlietz** [comment]
@cziegeler, That is what I tried before:

```
@ConsumerType
public interface ErrorHandler extends org.apache.sling.api.servlets.ErrorHandler {

}
```
Baseline output:
```
[ERROR]   Name                                               Type       Delta      New        Old        Suggest    If Prov.
[ERROR]   org.apache.sling.engine                            PACKAGE    UNCHANGED  2.6.0      2.6.0      ok         -
[ERROR]   org.apache.sling.engine.jmx                        PACKAGE    UNCHANGED  1.1.1      1.1.1      ok         -
[ERROR] * org.apache.sling.engine.servlets                   PACKAGE    MAJOR      2.0.9      2.0.9      3.0.0      2.1.0
```

**Comment by cziegeler** [comment]
This clearly shows that tooling is great but not always right; we can override the baseline check for this case, get the release out and then remove the override.

**Comment by kwin** [comment]
> but not always right

What makes you think that the tool is wrong here? This is IMHO breaking binary compatibility according to https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html#jls-13.5.

**Comment by oliverlietz** [comment]
> This clearly shows that tooling is great but not always right; we can override the baseline check for this case, get the release out and then remove the override.

Pushed with ignored baseline check for `org.apache.sling.engine.servlets`.

**Comment by oliverlietz** [comment]
@cziegeler, Do you see any chance to proceed with option 2 from [SLING-11728](https://issues.apache.org/jira/browse/SLING-11728)?

**Pull request merged**
